services:
  app:
    build:
      context: ./docker/go
    container_name: go-ipr-app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
    tty: true

  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
