services:
  app:
    build:
      context: ./docker/go
    container_name: go-ipr-app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - db
    tty: true
    networks:
      - app_network

  db:
    image: postgres:14
    container_name: go-ipr-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data/:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
