definitions:
  create.Command:
    properties:
      date:
        type: string
      dateTimeFrom:
        type: string
      dateTimeTo:
        type: string
      description:
        type: string
    type: object
  create.command:
    properties:
      Email:
        type: string
      Password:
        type: string
    type: object
  create_policy.Command:
    properties:
      approvable:
        type: boolean
      halfDay:
        type: boolean
      name:
        type: string
    type: object
  login.command:
    properties:
      Email:
        type: string
      Password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/daily-activities:
    post:
      consumes:
      - application/json
      description: This endpoint allows creating a new resource with a provided JSON
        payload.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/create.Command'
      produces:
      - application/json
      responses:
        "201":
          description: Created resource Id
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid JSON
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new daily-activity
      tags:
      - daily-activity
  /api/daily-activity/{id}:
    delete:
      description: Deletes a daily activity by its Id.
      parameters:
      - description: The Id of the daily activity
        in: query
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Delete Daily Activity
      tags:
      - daily-activity
  /api/day-off/policies:
    post:
      consumes:
      - application/json
      description: This endpoint allows creating a new resource with a provided JSON
        payload.
      parameters:
      - description: Request payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/create_policy.Command'
      produces:
      - application/json
      responses:
        "201":
          description: Created resource Id
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid JSON
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new day off policy
      tags:
      - day-off
  /api/users:
    post:
      consumes:
      - application/json
      description: Accepts JSON input and creates a new user, returning the user Id.
      parameters:
      - description: User creation payload
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/create.command'
      produces:
      - application/json
      responses:
        "201":
          description: User Id
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid JSON
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new user
      tags:
      - User
  /users/login:
    post:
      consumes:
      - application/json
      description: Handles user login by processing login commands, setting session,
        and returning the user Id.
      parameters:
      - description: User login command
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/login.command'
      produces:
      - application/json
      responses:
        "200":
          description: User Id
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid JSON
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: User Login Handler
      tags:
      - User
swagger: "2.0"
